### ISSUE TITLE
Pre-Trained Model

### ISSUE THREAD

**Issue by Alexmhack** [overwindows/SemanticCodeSearch#2]
Hi @overwindows, great work and thanks for sharing through this repo!

Can you share the pre-trained model and its related files??

**Comment by overwindows** [comment]
Sorry for very late response, 

Please find the model here
https://api.wandb.ai/files/wuchen/SemanticCodeSearch/1fpfl6dq/neuralbow_hybrid-2020-07-05-13-43-57_model_best.pkl.gz


For related project files, please find here 
https://wandb.ai/wuchen/SemanticCodeSearch/runs/1fpfl6dq/overview?workspace=user-wuchen
