### ISSUE TITLE
CodeTrans

### ISSUE THREAD

**Issue by xxgj** [overwindows/SemanticCodeSearch#3]
Hi @overwindows ,

Thanks for sharing your brilliant work!

However, I got an error when I tried to run the server:

```bash
~/g/SemanticCodeSearch (master)> python3 -m server.main
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/xxgj/github/SemanticCodeSearch/server/main.py", line 7, in <module>
    from server.code_trans import CodeTrans
```

The error occurred at https://github.com/overwindows/SemanticCodeSearch/blob/master/server/main.py#L7 .

It seems that I could not find `server.code_trans` on [master branch](https://github.com/overwindows/SemanticCodeSearch/tree/master/server). After reading your code, I find that this module does not seem to be much related to `SemanticCodeSearch`. Is it okay to just remove related code?

Please correct me if I mistake anything.

Thanks in advance!

Regards,
xxgj

**Comment by overwindows** [comment]
Hi @xxgj 

Sorry for the inconvenience, it's my mistake.

I've updated the repo and removed unnecessary libraries.

Any further questions please let me know.

Thanks

BR/Chen
